### ISSUE TITLE
can't find keycloak adapter in gravitee resources

### ISSUE THREAD

**Issue by natman** [gravitee-io/Tool-In-Action-2018#2]
Hello,
I follow your devfest demo, but I'm stuck at the type resource, where I can't fing the keycloak adapter type.

I noticed this volume that contains the gravitee-resource-oauth2-provider-keycloak-1.0.0-SNAPSHOT.zip plugin so it seems to be present
./plugins:/opt/graviteeio-gateway/plugins-ext

So I decided to build the 1.3.0 one but it doesn't work no more, even after restarting the tia_gateway.

**Comment by natman** [comment]
that's okay, I found the issue, each plugin inside /opt/graviteeio-gateway/plugins-ext must be owned by the user gravitee to be deployed. it is done by changing the owner of in ./plugins to 1000:1000 outside of the container.
Everything is okay now, and I managed to easily connect gravitee to keycloak oauth2 authentication.

**Comment by brasseld** [comment]
Hi @natman 

Sorry but I've missed your previous message.

We are working on some improvements for our Docker images (better support of openshift, no more user 1000, ...).
